spring.application.name=MailSender

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=d.yagnesh555@gmail.com
spring.mail.password= msyt cfny hydi afuo
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true